name: Publish release

on:
  push:
    tags:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install Yarn
      run: npm i yarn --global

    - name: Install Json
      run: npm i json --global

    - name: Install Packages
      run: yarn install --frozen-lockfile

    - name: Prepare release
      run: |
        VERSION=8.5.2
        echo "Preparing release $VERSION"
        npm version --no-git-tag-version --allow-same-version $VERSION
        git add package.json
        git commit -m "Bump version $VERSION"
        git push --no-verify

    - name: Publish
      run: |
        npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
        npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
