name: Publish release

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      DOCKERFILE: Dockerfile
      IMAGENAME: mermaid-cli
      DOCKER_IO_REPOSITORY: minlag/mermaid-cli

    steps:
    - uses: actions/checkout@v1
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install Yarn
      run: npm i yarn --global

    - name: Build the package
      run: | 
        yarn
        chmod 755 copy_modules.sh
        ./copy_modules.sh
        yarn prepublishOnly

    - name: Get release version
      run: echo ::set-env name=RELEASE_VERSION::$(echo 8.5.4)

    - name: Publish to npmjs
      run: |
        npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
        npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish to Github Registry
      uses: elgohr/Publish-Docker-Github-Action@2.17
      with:
        name: $GITHUB_REPOSITORY/${{env.IMAGENAME}}
        username: $GITHUB_ACTOR
        password: ${{secrets.GITHUB_TOKEN}}
        registry: docker.pkg.github.com
        dockerfile: ${{env.DOCKERFILE}}
        buildargs: ${{env.RELEASE_VERSION}}
        snapshot: false
        tags: "latest,${{env.RELEASE_VERSION}}"

    - name: Publish to Docker.io Registry
      uses: elgohr/Publish-Docker-Github-Action@2.17
      with:
        name: ${{env.DOCKER_IO_REPOSITORY}}
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        dockerfile: ${{env.DOCKERFILE}}
        buildargs: ${{env.RELEASE_VERSION}}
        snapshot: false
        tags: "latest,${{env.RELEASE_VERSION}}"

    - name: Post deployment tests
      run: for i in $(ls test/*.mmd); do docker run -v $(pwd):/data ${{env.DOCKER_IO_REPOSITORY}}:${{env.RELEASE_VERSION}} -i /data/$i; done  
      
    # For manual inspection of the generated artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: output
        path: ./test
